CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, phone VARCHAR(30) UNIQUE NOT NULL, role VARCHAR(30) NOT NULL, password TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS donations (id BIGSERIAL PRIMARY KEY, donor_name VARCHAR(150) NOT NULL, phone VARCHAR(30), amount NUMERIC(12,2) NOT NULL, payment_method VARCHAR(50), payment_status VARCHAR(30) DEFAULT 'Paid', collected_by BIGINT REFERENCES users(id) ON DELETE SET NULL, donated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pooja_timings (id BIGSERIAL PRIMARY KEY, date DATE NOT NULL, time TIME NOT NULL, description TEXT);
CREATE TABLE IF NOT EXISTS programs (id BIGSERIAL PRIMARY KEY, program_name VARCHAR(200) NOT NULL, program_date DATE NOT NULL, program_time TIME NOT NULL, description TEXT);
CREATE TABLE IF NOT EXISTS previous_celebrations (id BIGSERIAL PRIMARY KEY, year INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT, image_url TEXT, video_url TEXT);
CREATE TABLE IF NOT EXISTS member_messages (id BIGSERIAL PRIMARY KEY, sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE, sender_name VARCHAR(100) NOT NULL, message TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS google_meet_settings (id INTEGER PRIMARY KEY CHECK (id = 1), meet_url TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
